spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlHHH123...
    url: jdbc:mysql://gz-cdb-fg5tqemn.sql.tencentcdb.com:63279/cmas
  main:
    allow-circular-references: true
server:
  servlet:
    context-path: "/api"
  port: 8188
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.phosa.cmas.model
